// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import MenuController from "./menu_controller";
application.register("menu", MenuController);

import DrawingController from "./drawing_controller";
application.register("drawing", DrawingController);

import OceanController from "./ocean_controller";
application.register("ocean", OceanController);
